export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Qraft Labs",
  description: "Qraft Labs pioneers groundbreaking research at the intersection of the future of work and educational technology (edtech). Our innovative studies and insights drive transformative solutions for navigating the evolving landscape of work and learning. Explore our cutting-edge research to stay ahead in the rapidly changing world of work and education",
  slogan: "",
  url: "https://labs.qraftacademy.com/",
  logo: {
    dark: "",
    light: "",
  },
  links: {
    github: "https://github.com/kolynzb/qraft-labs",
  },
  contacts: {
    tel: ["+256-701-092-815"],
    email: "info@kawu.ug/",
    tele: "+256701092815",
    address: "Plot 851 Serumaga Road, Bukoto, Kampala, Uganda",
  },
};


export const seoKeywords = [
  "education technology",
  "online learning",
  "e-learning platforms",
  "digital education",
  "remote learning",
  "virtual classrooms",
  "adaptive learning",
  "personalized learning",
  "educational technology trends",
  "future of work",
  "workplace automation",
  "remote work",
  "digital skills",
  "automation technology",
  "gig economy",
  "telecommuting",
  "workplace flexibility",
  "research",
  "academic research",
  "scientific research",
  "research studies",
  "research papers",
  "research methodologies",
  "research findings",
  "Edtech",
  "Atuhaire Collins Benda",
  "Tech blog",
  "Andrew Tugume", "educational apps",
  "learning management systems",
  "online courses",
  "distance education",
  "blended learning",
  "virtual reality in education",
  "artificial intelligence in education",
  "STEM education",
  "professional development",
  "digital transformation",
  "workforce skills",
  "job automation",
  "remote collaboration",
  "flexible work arrangements",
  "work-life balance",
  "innovation research"
]